# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Proto/master.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12Proto/master.proto\",\n\x0ePutDataRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"M\n\x0fPutDataResponse\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x14\n\x0cresponseCode\x18\x02 \x01(\x05\x12\x17\n\x0fresponseMessage\x18\x03 \x01(\t\"\x1d\n\x0eGetDataRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\\\n\x0fGetDataResponse\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x14\n\x0cresponseCode\x18\x03 \x01(\x05\x12\x17\n\x0fresponseMessage\x18\x04 \x01(\t2d\n\x06master\x12,\n\x07putData\x12\x0f.PutDataRequest\x1a\x10.PutDataResponse\x12,\n\x07getData\x12\x0f.GetDataRequest\x1a\x10.GetDataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Proto.master_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PUTDATAREQUEST']._serialized_start=22
  _globals['_PUTDATAREQUEST']._serialized_end=66
  _globals['_PUTDATARESPONSE']._serialized_start=68
  _globals['_PUTDATARESPONSE']._serialized_end=145
  _globals['_GETDATAREQUEST']._serialized_start=147
  _globals['_GETDATAREQUEST']._serialized_end=176
  _globals['_GETDATARESPONSE']._serialized_start=178
  _globals['_GETDATARESPONSE']._serialized_end=270
  _globals['_MASTER']._serialized_start=272
  _globals['_MASTER']._serialized_end=372
# @@protoc_insertion_point(module_scope)
